update cd workflows

diff --git a/.github/workflows/cd_production.yml b/.github/workflows/cd_production.yml
--- a/.github/workflows/cd_production.yml
+++ b/.github/workflows/cd_production.yml
@@ -48,13 +48,10 @@ jobs:
             docker compose -f docker-compose.yml up -d
             echo "Code is deployed for tag $DEPLOY_TAG."
 
-      - name: Run migration
-        timeout-minutes: 10
-        run: |
-          docker compose -f docker-compose.yml exec backend alembic upgrade head || {
-            echo "Migration failed, checking logs..."
-            docker compose -f docker-compose.yml logs backend
-            exit 1
-          }
+            docker compose -f docker-compose.yml exec -T backend alembic upgrade head || {
+              echo "Migration failed, checking logs..."
+              docker compose -f docker-compose.yml logs backend
+              exit 1
+            }
 
-          echo "Deployment completed."
+            echo "Deployment completed."
