update cd for staginga and prod

diff --git a/.github/workflows/cd_production.yml b/.github/workflows/cd_production.yml
--- a/.github/workflows/cd_production.yml
+++ b/.github/workflows/cd_production.yml
@@ -46,4 +46,15 @@ jobs:
 
             docker compose -f docker-compose.yml down || true
             docker compose -f docker-compose.yml up -d
-            echo "Deployment of tag $DEPLOY_TAG completed."
+            echo "Code is deployed for tag $DEPLOY_TAG."
+
+      - name: Run migration
+        timeout-minutes: 10
+        run: |
+          docker compose -f docker-compose.yml exec backend alembic upgrade head || {
+            echo "Migration failed, checking logs..."
+            docker compose -f docker-compose.yml logs backend
+            exit 1
+          }
+
+          echo "Deployment completed."
