Update docker configurations (#328)
* update docker configurations

* update cd

* minor update

* feedback fixes

* update cd

* add cd for staging

* run migrations

* update cd for staginga and prod

* update cd workflows

diff --git a/.github/workflows/cd_production.yml b/.github/workflows/cd_production.yml
--- a/.github/workflows/cd_production.yml
+++ b/.github/workflows/cd_production.yml
@@ -1,10 +1,13 @@
 name: Deploy to Production tag
 
+permissions:
+  contents: read
+
 # Trigger only when a tag matching v* is pushed (eg v1.2.3)
 on:
   push:
     tags:
-      - 'v*'
+      - "v*"
 
 jobs:
   deploy:
@@ -13,7 +16,7 @@ jobs:
     steps:
       - name: Checkout (for logs)
         uses: actions/checkout@v6
-        
+
       - name: Set deployment tag
         id: set_tag
         run: |
@@ -24,24 +27,31 @@ jobs:
           echo "DEPLOY_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
           fi
           echo "Will deploy tag: $DEPLOY_TAG"
-          
+
       - name: Deploy via SSH (tag-based)
         uses: appleboy/ssh-action@v1.2.4
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
-        
+
           script: |
             DEPLOY_TAG="${{ env.DEPLOY_TAG }}"
             set -euxo pipefail
             cd /home/ubuntu/sashakt-core
-        
 
             git fetch --all --tags --prune
             # use exported DEPLOY_TAG (it will be like "v1.0.2")
             git checkout "tags/$DEPLOY_TAG" -f || git checkout -B "deploy-$DEPLOY_TAG" "tags/$DEPLOY_TAG"
-            cp -v ../yaml-store/*.yml .
-            docker compose down || true
-            docker compose up -d
-            echo "Deployment of tag $DEPLOY_TAG completed."
+
+            docker compose -f docker-compose.yml down || true
+            docker compose -f docker-compose.yml up -d
+            echo "Code is deployed for tag $DEPLOY_TAG."
+
+            docker compose -f docker-compose.yml exec -T backend alembic upgrade head || {
+              echo "Migration failed, checking logs..."
+              docker compose -f docker-compose.yml logs backend
+              exit 1
+            }
+
+            echo "Deployment completed."
